### ISSUE TITLE
Windows cpp performance

### ISSUE THREAD

**Issue by immersive** [restorer/zame-haxe-particles#11]
Hello and thanks for the library.

Performance on the cpp target is currently much worse than other targets, contrary to expectations.

I have tried rolling it back to find out which at version of lime/openfl/hxcpp/haxe performance dropped but I've not been able to find a working older combination of them.

![recording 5](https://user-images.githubusercontent.com/26234523/39007200-282648c0-43fd-11e8-8e62-971d05b4970d.gif)

**Comment by maaniv** [comment]
Try to use TilemapParticleRenderer instead of DefaultParticleRenderer

**Comment by restorer** [comment]
In older version (now it is under `openfl4` branch) `SpritesRenderer` was used for cpp, because tilemap renderer in OpenFl 4.x doesn't support color transform.

Currently `TilemapRenderer` is used for every target except flash, and performance should be good.
