### ISSUE TITLE
Diff for enabling color in TilemapParticleRenderer

### ISSUE THREAD

**Issue by maaniv** [restorer/zame-haxe-particles#12]
In latest OpenFL tile might have color transform data, that diff simply uses it to color the particles.
[tilemap-color-enabled-diff.txt](https://github.com/restorer/zame-haxe-particles/files/1990931/tilemap-color-enabled-diff.txt)

**Comment by restorer** [comment]
Interesting, I should try it.

**Comment by restorer** [comment]
Update. I'm not ignoring this improvement 😄 But unfortulately at the moment I have absolutely no free time to merge it and test everything properly.

**Comment by restorer** [comment]
Finally merged
