### ISSUE TITLE
Request: Add a TileContainer particle renderer

### ISSUE THREAD

**Issue by miltoncandelero** [restorer/zame-haxe-particles#13]
I've seen it shouldn't be too hard to implement a renderer based on a TileContainer.

By doing so we allow particles to live inside a user-controlled Tilemap and allow for better integration to games that rely on Tilemap for rendering.

If nobody tackles this task I will return and do it when I get the time.

Thank you for the amazing lib!

**Comment by restorer** [comment]
Hi! Currently I'm working on other project, so have no time to implement it by myself, but PR are welcome!

**Comment by miltoncandelero** [comment]
There I sent #15 
didn't change the haxelib.json because I didn't know if I should bump the minor or the patch version number.

**Comment by restorer** [comment]
Merged. Thanks again.

I have a question about `removeEvent()` method - https://github.com/restorer/zame-haxe-particles/blob/master/org/zamedev/particles/renderers/TileContainerParticleRenderer.hx#L228

```
// Necesary because weak listeners are not implemented.
public function removeEvent() {
    if (dataList.length == 0 && !manualUpdate) {
        openfl.Lib.current.stage.removeEventListener(Event.ENTER_FRAME, onEnterFrame);
    }
}
```

Is it true that this method should be called when this renderer is removed from the parent `TileContainer` or `Tilemap` to remove event listener from the stage? If yes, than probably there is an error - if user remove this renderer while dataList is not empty, than listener will not be removed. I guess that this method should look like this:

```
public function removeEvent() {
    if (!manualUpdate) {
        openfl.Lib.current.stage.removeEventListener(Event.ENTER_FRAME, onEnterFrame);
    }
}
```

P.S. Would you mind if I rename it to `onRemovedFromParent()`?

**Comment by miltoncandelero** [comment]
You are right about the condition and I have no problems with the renaming 👍

**Comment by restorer** [comment]
Done.
