### ISSUE TITLE
Demo not working on Safari, OS X

### ISSUE THREAD

**Issue by synthmeat** [restorer/zame-haxe-particles#3]
Console logs error:

```
createImageData sample.js:165
TypeError: undefined is not an object (evaluating a.__srcContext.getImageData')
```

**Comment by restorer** [comment]
Not reproducible in Safari 9.0.1 (11601.2.7.2) in El Capitan

**Comment by synthmeat** [comment]
Same versions here. Toggled few extensions, seems like uBlock is causing it. Not sure why, but as far as I'm concerned, this isn't an issue with this great lib.

Thanks for quick response!
