### ISSUE TITLE
Zame-Particles for openfl 4

### ISSUE THREAD

**Issue by vega-7** [restorer/zame-haxe-particles#6]
Hello, first of all thanks a lot for this amazing library  i used this on my android game, hulapuzzle. 

i noticed that zame particles library isnt working with the new openfl 4.0, this because  the class tilesheet and others dependecy class were removed from this version,.. there is a chance to make this library works with the new openfl 4.0 version?

thanks again for your code, time , and answer, 

this library was really helpful to me, and i hope it will continue be helpful

Att.

vega7.co

**Comment by restorer** [comment]
Thanks!

Migrating to OpenFL 4 is planned, but currently I have no free time (I will appreciate, if someone will send pull request).

Currently (as work-around) you can use `SpritesParticleRenderer`.

**Comment by ghost** [comment]
I'm going to look for a way to fix this since my project heavily relies on Zame-Particles & new features of OpenFL. I'll send you a pull request if I'll be able to make a good/non-hacky fix.

**Comment by restorer** [comment]
Thanks!

**Comment by ghost** [comment]
I've been able to make a quick hacky fix by extending the Tilemap class to meet the needs of the renderer, but it affected performance so I can't really render thousands upon thousands of particles like I could before :( Well, all hope is with you, restorer. If you fix the particle system for us I'll make sure to send a donation your way :) Please find time to fix it!

PS: using SpritesParticleRenderer is not an option - many settings are omitted and the performance is God-awful

**Comment by restorer** [comment]
Bad news, everyone.

I tried Tilemap / Tilesheet, but:
- it doesn't support rotating about arbitrary pivot point;
- it doesn't support color transform;
- it doesn't support blending modes.

Will try to use drawTriangles - that will fix rotating issues, but still no colors and blending modes 😭

**Comment by ghost** [comment]
Just FYI I've been able to extend the Tile, Tilemap, Tilesheet classes and override the setters that set rotation and introduce a pivot point. Color transform will take more work since it will require to extend the part in the _internal package :( I'm too lazy to do it myself to be honest

**Comment by restorer** [comment]
I use slightly different approach (modify tile.matrix directly).

Can you share the code?

**Comment by ghost** [comment]
Sure, I'll do it tomorrow when I get to the office

**Comment by restorer** [comment]
Just added pivot point support - https://github.com/restorer/zame-haxe-particles/commit/e0acc4774fd2822d09bcd64bc55f14a497f72af0

So basically we have Tileset / Tilemap support, but:
1. ~~It slower than drawTiles in OpenFL 3~~ Actually faster.
2. Currently Tileset / Tilemap has no support for color modifications 😿

**Comment by ghost** [comment]
I'm sorry but my company didn't want me to publish any code. But since you've already added the pivot point I guess you don't need it anyway.

**Comment by loudoweb** [comment]
> Currently Tileset / Tilemap has no support for color modifications

That's a feature I also need for my library. I wonder if it's possible to do like this:
1. override `Tile` to add color data
2. override `GLTilemap` to send color data as attribute to the shader (maybe add also and activation attribute as a boolean). 
3. create a vertex shader that transforms this attribute into a varying (maybe add also and activation attribute as a boolean) to pass into the fragment shader
4. create a fragment shader that manipulates the color based on the varying color (+ varying activation that allows to decide to use color transformation or not in the shader)

This way it allows to render in a single pass.

There is another way (maybe simplier) to do that with uniform instead of attributes but it will need one drawcall per Tile instead of one drawcall per Bitmap.

**Comment by restorer** [comment]
Unfortunately I need cross-target API, not just webgl (for GL I have GLViewParticleRenderer)

**Comment by ghost** [comment]
I seems like a headache but I guess you could just make conditional compilation and choose what class compiles utilizing typedefs.

**Comment by restorer** [comment]
Already done :) GLViewParticleRenderer is used when possible.

**Comment by ramsestom** [comment]
Hi

  I wanted to use you lib with openfl 4 on cpp targets to render some "evaporation" effect. The html5 demo looks really good but, from what I have seen on the README page, the rendering with openfl 4 on cpp targets wouldn't be so good and fluid for now. Am I right?
What method would you recommend to use to render something similar to the example 10/17 of your demo with openfl 4 on cpp targets?

**Comment by restorer** [comment]
@ramsestom Try Sprites renderer in the latest version.

**Comment by loudoweb** [comment]
Hello, Tiles from `Tilemap `have colorTransform property now \o/

**Comment by restorer** [comment]
Cool! We should try to use it.
