### ISSUE TITLE
In html5 target the particles are white?

### ISSUE THREAD

**Issue by Arthur-W-White** [restorer/zame-haxe-particles#9]
Hi,
In most targets the particle are properly colorized but in html5 they are white?

**Comment by restorer** [comment]
Do you use `-Dcanvas` mode? Look at renderers comparison in [README.md](https://github.com/restorer/zame-haxe-particles/blob/master/README.md) - html5 with `-Dcanvas` doesn't support color effects.

But `-Dwebgl` and `-Ddom` supports.

**Comment by Arthur-W-White** [comment]
Thanks! I didn't apply a flag but it works perfectly with -Dwebgl. :D
